name: CI Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:   
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Configure python
      run: |         
        python -m pip install --upgrade pip setuptools wheel pytest
    - name: Generate cmake 
      run: |
        echo Start generate CMake
        cd $GITHUB_WORKSPACE
        generate.cmd        
      shell: cmd
    - name: Build and test
      run: |
        echo Start Build
        cd $GITHUB_WORKSPACE
        runbuild.cmd
      shell: cmd
