name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Generate cmake 
      run: |
        echo Start generate CMake
        cd $GITHUB_WORKSPACE
        generate.cmd        
      shell: cmd
    - name: Build and test
      run: |
        echo Start Build
        cd $GITHUB_WORKSPACE
        runbuild.cmd
      shell: cmd
